#!/bin/sh
# Provision broker credentials for the local Docker dev stack (docker-compose.yml).
#
# WHY THIS EXISTS: the dev broker used to run `allow_anonymous true`, so any host on the Wi-Fi could
# subscribe to every child's 10 Hz feed or publish forged telemetry that the server would accept,
# server-stamp and persist as authoritative (audit §4.6). The stack now mounts the SAME authenticated
# config the field broker uses (mosquitto.conf + ft.acl, `allow_anonymous false`), which needs a
# password file — and ft.passwd is a secret, so it is gitignored and cannot ship in the repo.
#
# Run this ONCE before the first `docker compose up`, and again whenever you add a wearable:
#
#     ./server/mosquitto/dev-provision.sh            # server account + player 01
#     ./server/mosquitto/dev-provision.sh 01 02 07   # server account + those player ids
#
# It writes:
#   server/mosquitto/ft.passwd   the hashed accounts the broker checks   (gitignored)
#   .env                         MQTT_USERNAME/MQTT_PASSWORD for compose (gitignored)
#
# and PRINTS each wearable's password once — that is the only time you see it, so copy it into the
# device over the serial `enroll` console (`set player <id>` / `set mqttpass <pw>` / `save`; see
# firmware/README.md, ADR-0014). Re-run with --force to rotate everything if you lose them.
#
# DEV-GRADE, and deliberately so: the generated passwords are passed to mosquitto_passwd on a command
# line (briefly visible to `ps` on this machine) and printed to your terminal scrollback. That is the
# right trade for a bench stack on your own laptop; the field broker's accounts should be created by
# hand with the interactive `mosquitto_passwd` (no -b), per server/mosquitto/README.md.
set -eu

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO=$(CDPATH= cd -- "$DIR/../.." && pwd)
PASSWD="$DIR/ft.passwd"
ENV_FILE="$REPO/.env"

FORCE=0
PLAYERS=""
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "unknown option: $arg" >&2; exit 2 ;;
    # A player id is the MQTT username AND the %u in ft.acl, so keep it to the same shape the firmware
    # enrolls and the topic carries: 1-16 chars of [A-Za-z0-9_-]. A rejected id here would otherwise
    # become an account that can never match its own topic.
    *) case "$arg" in
         *[!A-Za-z0-9_-]*) echo "invalid player id '$arg' (allowed: A-Z a-z 0-9 _ -)" >&2; exit 2 ;;
       esac
       if [ ${#arg} -gt 16 ]; then echo "player id '$arg' too long (max 16)" >&2; exit 2; fi
       PLAYERS="$PLAYERS $arg" ;;
  esac
done
[ -n "$PLAYERS" ] || PLAYERS=" 01"

if [ -e "$PASSWD" ] && [ "$FORCE" -eq 0 ]; then
  echo "refusing to overwrite $PASSWD (it holds the accounts your devices are already enrolled with)." >&2
  echo "Rotate everything with:  $0 --force$PLAYERS" >&2
  exit 1
fi

# Prefer a host mosquitto_passwd; otherwise borrow the one inside the broker image we already run, so
# this works on a machine with only Docker installed (`brew install mosquitto` is optional).
if command -v mosquitto_passwd >/dev/null 2>&1; then
  mp() { mosquitto_passwd "$@"; }
elif command -v docker >/dev/null 2>&1; then
  # -u 0 so the file lands writable in the bind mount regardless of the image's default user.
  mp() { docker run --rm -u 0 -v "$DIR:/work" eclipse-mosquitto:2 mosquitto_passwd "$@"; }
  PASSWD_IN_MP="/work/ft.passwd"
else
  echo "need either mosquitto_passwd (brew install mosquitto) or docker" >&2
  exit 1
fi
TARGET="${PASSWD_IN_MP:-$PASSWD}"

# Alphanumeric only: this value is interpolated by docker compose out of .env, where a '$' would be
# eaten as a variable reference and silently truncate the password (the broker would then reject the
# server, which looks like a broker fault rather than a quoting bug).
genpw() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32; }

rm -f "$PASSWD"
INGEST_PW=$(genpw)
mp -b -c "$TARGET" ingest "$INGEST_PW"

echo
echo "Wearable credentials — copy each into that device NOW (serial 'enroll' console):"
echo
for p in $PLAYERS; do
  PW=$(genpw)
  mp -b "$TARGET" "$p" "$PW"
  echo "  player $p    set player $p    set mqttpass $PW"
done
echo

# Only the ingest account goes in .env — it is what compose injects into the server container. The
# wearable passwords are never stored on this machine; they live in each device's NVS.
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by server/mosquitto/dev-provision.sh — gitignored, do not commit.
# Read automatically by docker compose (repo-root .env) and injected into the server container so it
# can authenticate to the broker as the read-only 'ingest' account (ft.acl: read football-trackers/#).
MQTT_USERNAME=ingest
MQTT_PASSWORD=$INGEST_PW
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true
# 0600 on both broker files: mosquitto 2.1 WARNS that they are world-readable and says future versions
# will refuse to load them — i.e. the next image bump would stop the broker. ft.acl is git-tracked, so a
# fresh clone brings back 0644 and only this script can put it right; ft.passwd holds password hashes and
# has no business being readable by every account on the machine either.
# LINUX NOTE: Docker Desktop (macOS) grants the container access regardless of uid, so 0600 is fine there.
# On a Linux host the bind mount enforces real uids and the broker (uid 1883) could not read a 0600 file
# owned by you — use `sudo chown 1883:1883 server/mosquitto/ft.passwd server/mosquitto/ft.acl` in that case.
chmod 600 "$PASSWD" "$DIR/ft.acl" 2>/dev/null || true

echo "wrote $PASSWD (accounts: ingest,$(echo "$PLAYERS" | tr -s ' ' ',' | sed 's/^,//'))"
echo "wrote $ENV_FILE (MQTT_USERNAME/MQTT_PASSWORD for the server container)"
echo
echo "Next:  docker compose up -d      # the broker now refuses anonymous clients"
